---
- name: download zookeeper binary file
  unarchive:
    src: http://ftp.wayne.edu/apache/zookeeper/stable/zookeeper-3.4.10.tar.gz
    dest: /opt/
    remote_src: True
- name: create link for root folder
  file: state=link src=/opt/zookeeper-3.4.10 dest=/opt/zookeeper
- name: set zookeeper nohub log file path
  lineinfile: 
     path: /opt/zookeeper/bin/zkEnv.sh 
     insertafter: '^ZOOKEEPER_PREFIX'
     line: ZOO_LOG_DIR="/var/log/zookeeper/"
- name: copy init script
  copy: 
    src: zookeeper
    dest: /etc/init.d/zookeeper
    mode: 0755
- name: create data and log file
  file: state=directory path={{ item }} owner=nobody group=nobody
  with_items:
    - /var/lib/zookeeper
    - /var/log/zookeeper
- name: generate zoo.cfg
  template: src={{item.name}} dest={{item.path}} owner=nobody group=nobody
  with_items:
     - { name: zoo.cfg.j2,path: /opt/zookeeper/conf/zoo.cfg}
     - { name: myid.j2,path: /var/lib/zookeeper/myid}
  notify: start zookeeper
