---
- block:
    - name: "end play "
      debug:
        msg: "slaveof is not same as redismaster"
    - meta: end_play
  when: "( redismaster is defined ) and ( hostvars[groups['redis'][1]]['slaveof'] != redismaster )"
- set_fact: 
     redis_sentinel: redis-sentinel
  when: "redismaster is defined"
- name: install make and gcc
  yum: name={{item}} state=present
  with_items:
     - make
     - gcc
- name: download redis src file
  unarchive:
    src: http://download.redis.io/redis-stable.tar.gz
    dest: /opt/
    remote_src: True
- name: compile and install latest redis
  shell: "{{ item }}"
  args: 
    chdir: /opt/redis-stable
  with_items:
    - make distclean
    - make  
    - make PREFIX=/usr/ install
- name: create data and log file
  file: state=directory path={{ item }} owner=nobody group=nobody
  with_items:
    - /var/lib/redis
    - /var/log/redis
    - /etc/redis
- name: copy configure files
  template:
    src: "{{ item }}"
    dest: /etc/redis/{{ item[0:-3] }}
    owner: nobody 
    group: nobody
  with_items:
     - redis.conf.j2
     - sentinel.conf.j2
  notify: start redis
- name: copy init script
  copy: 
    src: "{{ item }}"
    dest: /etc/init.d/
    mode: 0755
  with_items:
     - redis-sentinel
     - redis-server
  notify: start redis
