---
- block:
    - name: "end play "
      debug:
        msg: "slaveof is not same as redismaster"
    - meta: end_play
  when: "( redismaster is defined ) and ( hostvars[groups['redis'][1]]['slaveof'] != redismaster )"
- set_fact: 
     redis_sentinel: redis-sentinel
  when: "redismaster is defined"
- name: install make and gcc
  yum: name={{item}} state=present
  with_items:
     - make
     - gcc
- stat: path=/opt/redis-3.2.11
  register: redis_src
- name: download redis 3.2.11 src file
  unarchive:
    src: http://download.redis.io/releases/redis-3.2.11.tar.gz
    dest: /opt/
    remote_src: True
  when: "redis_src.stat.exists == False"
- name: compile and install latest redis
  shell: "{{ item }}"
  args: 
    chdir: /opt/redis-3.2.11
  with_items:
    - make distclean
    - make  
    - make PREFIX=/usr/ install
- name: create data and log file
  file: state=directory path={{ item }} owner=nobody group=nobody
  with_items:
    - /var/lib/redis
    - /var/log/redis
    - /etc/redis
- name: copy configure files
  template:
    src: "{{ item }}"
    dest: /etc/redis/{{ item[0:-3] }}
    owner: nobody 
    group: nobody
  with_items:
     - redis.conf.j2
     - sentinel.conf.j2
  notify: start redis
- name: replace zabbix monitoring script
  lineinfile:
     path:  /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
     regexp: 'redisrole'
     line: "UserParameter=redisrole,redis-cli -a {{redispass}} info replication|grep 'role:master' >>/dev/null&&echo 1||echo 0"
  when: redispass is defined and MNREDIS is defined
- name: copy init script for centos6
  copy: 
    src: "{{ item }}"
    dest: /etc/init.d/
    mode: 0755
  with_items:
     - "{{ redis_sentinel | default('redis-server') }}"
     - redis-server
  when: ansible_distribution_major_version == "6"
  notify: start redis
- name: copy init script for centos7
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    mode: 0755
  with_items:
     - "{{ redis_sentinel | default('redis-server') }}.service"
     - redis-server.service
  when: ansible_distribution_major_version == "7"
  notify: start redis 
