---
- name: download redis src file
  unarchive:
    src: http://download.redis.io/redis-stable.tar.gz
    dest: /opt/
    remote_src: True
- name: compile and install latest redis
  shell: "{{ item }}"
  args: 
    chdir: /opt/redis-stable
  with_items:
    - make  
    - make PREFIX=/usr/ install
#- name: install redis init script
#  shell: >
#         sudo REDIS_PORT=6379 REDIS_CONFIG_FILE=/etc/redis/redis.conf REDIS_LOG_FILE=/var/log/redis.log  
#         REDIS_DATA_DIR=/var/lib/redis/ REDIS_EXECUTABLE=`command -v redis-server` ./utils/install_server.sh&&chkconfig --del redis_6379&&mv /etc/init.d/redis_6379 //etc/init.d/redis&&
#         chkconfig --level 345 redis on
#  args:
#    chdir: /opt/redis-stable
- name: create data and log file
  file: state=directory path={{ item }} owner=nobody group=nobody
  with_items:
    - /var/lib/redis
    - /var/log/redis
    - /etc/redis
- name: copy configure files
  copy:
    src: "{{ item }}"
    dest: /etc/redis/
    owner: nobody 
    group: nobody
  with_items:
     - redis.conf
     - sentinel.conf
- name: copy init script
  copy: 
    src: "{{ item }}"
    dest: /etc/init.d/
    mode: 0755
  with_items:
     - redis-sentinel
     - redis-server
  notify: start redis
