---
- hosts: localhost
  gather_facts: no
  vars:
    ec2s:
      - VIP: 172.18.91.146
        ports:
           - 8000/8000
           - 1111/1111
           - 8081/8081
#      - VIP: 172.18.91.142
#        ports:
#           - 3333/3333
#           - 2222/2222
#  roles: 
#    - {role: alicloud}
