---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ec2s:
      - VIP: 172.18.91.139
        ports:
#           - ["TCP","8000/8000",'0.0.0.0/0']
#           - ["TCP","1111/1111","0.0.0.0/0"]
#           - ["TCP","8081/8081","0.0.0.0/0"]
           - ["ALL","-1/-1","192.168.128.0/24"]
  roles: 
    - {role: alicloud}
