---
- hosts: docker
  gather_facts: yes
  vars:
  tasks: 
  - name:
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    when: ansible_distribution_major_version == "7"
  - name: install docker-ce
    yum: name=docker-ce-17.09.1.ce state=present
    when: ansible_distribution_major_version == "7"
    notify: start docker
  handlers:
  - name: start docker
    service: name=docker state=restarted enabled=yes
