---
- hosts: kafka
  gather_facts: no
  vars: 
    cluster: true
    kafka_zk: 192.168.168.41:2181,192.168.168.42:2181,192.168.168.43:2181  
  roles: 
    - {role: kafka}
#- import_playbook: zookeeper.yml
#  when: cluster is defined and cluster == "true"
