---
- hosts: mesos
  gather_facts: yes
  vars: 
#    MESOS_cluster: true
#    MESOS_zk: zk://192.168.168.41:2181,192.168.168.42:2181,192.168.168.43:2181/mesos 
    mesos_master: 192.168.168.41:5050
  roles: 
    - {role: mesos}
#- import_playbook: zookeeper.yml
#  when: MESOS_CLUSTER is defined and MESOS_zk is defined
