---
- hosts: mongodb
  gather_facts: no
  vars:
    - ZABBIX_SERVER: 127.0.0.1
    - MONGO_new:
         user: spider
         db: convertor
         passwd: admin
         roles: dbOwner
    - DBLOGIN:
         user: admin
         db: admin
         passwd: xxx
  roles: 
    - {role: mongodb}
