---
- hosts: mysqlbackup
  gather_facts: yes
  vars:
     ansible_user: root
     MYSQL_backup:
         - user: dbbackup
           passwd: monitoring3445
           hosts:
            - 'localhost'
           privs:
            - "*.*:REPLICATION CLIENT,RELOAD"
            - "test%.*:SELECT"
     MYSQL_rootpwd: xdYt2ddd21o90
     keep_days: 7
  roles: 
    - {role: mysqlbackup}
