##ansible-playbook -i hosts  znfw.yml --extra-vars 'ansible_ssh_private_key_file=/opt/hzx/pro/yang.pem ansible_user=liu' -b --ask-become-pass
---
- import_playbook: common.yml
- import_playbook: redis.yml
- import_playbook: mongodb.yml
- import_playbook: python.yml
- hosts: java
  roles:
    - java
