---
- hosts: zookeeper
  gather_facts: no
  vars:
    - ZABBIX_SERVER: 127.0.0.1
    - ZKPS: 
        - ID: 1 
          IP: 192.168.168.44
        - ID: 2
          IP: 192.168.168.41
        - ID: 3 
          IP: 192.168.168.42
  roles: 
    - {role: zookeeper}
