---
- name: check active file status
  stat: path=/opt/apache-activemq-5.15.0/
  register: actpath
- name: download activemq-5.15 file
  unarchive:
    src: http://archive.apache.org/dist/activemq/5.15.0/apache-activemq-5.15.0-bin.tar.gz
    dest: /opt/
    remote_src: True
    owner: nobody
    group: nobody
  when: actpath.stat.islnk is not defined
- name: create link for root folder
  file: state=link src=/opt/apache-activemq-5.15.0 dest=/opt/apache-activemq
- name: copy init script
  copy:
    src: activemq
    dest: /etc/init.d/activemq
    mode: 0755
- name: create data and log file
  file: state=directory path={{ item }} owner=nobody group=nobody
  with_items:
    - /opt/apache-activemq/data/activemq-data
    - /opt/apache-activemq/data
- name: generate activemq.xml
  template: src={{item.name}} dest={{item.path}} owner=nobody group=nobody
  with_items:
     - { name: activemq.xml.j2,path: /opt/apache-activemq/conf/activemq.xml}
  notify: start activemq
