---
- name: end tasks if it's not centos7
  fail: msg='ensure you are running this on centos7 system'
  when: ansible_distribution_major_version != "7"
- name: 
  get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution_major_version == "7"
- name: install mesos repository
  yum: 
     name: http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm
     state: present
- name: install mesos-1.4.1
  yum: name=mesos-1.4.1 state=latest
#- name: install docker-ce
#  yum: name=docker-ce state=present
#  notify: start docker
- name: copy init script for centos7
  copy:
    src: mesos-{{mesos_role}}.service
    dest: /etc/systemd/system/
    mode: 0755
  notify: start mesos-{{mesos_role}}
- name: generate credentials file
  template:
      src: credentials.j2
      dest: /etc/mesos-master/credentials
  when: MESOS_authenticate_frameworks is defined and mesos_role == "master"
- name: copy over configuration file
  template:
      src: "{{mesos_role}}.j2"
      dest: /etc/mesos-{{mesos_role}}.env
  notify: start mesos-{{mesos_role}}
