---
- name: 
  get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_distribution_major_version == "7"
- name: install mesos repository
  yum: 
     name: http://repos.mesosphere.com/el/{{ansible_distribution_major_version}}/noarch/RPMS/mesosphere-el-repo-{{ansible_distribution_major_version}}-3.noarch.rpm
     state: present
- name: install mesos-1.3.0-2.0.3
  yum: name=mesos-1.3.0-2.0.3 state=present
- name: install docker-ce
  yum: name=docker-ce state=present
  when: ansible_distribution_major_version == "7"
- name: copy init script for centos7
  copy:
    src: mesos-{{mesos_role}}.service
    dest: /etc/systemd/system/
    mode: 0755
  when: ansible_distribution_major_version == "7"
  notify: start mesos-{{mesos_role}}
- name: copy over configuration file
  template:
      src: "{{mesos_role}}.j2"
      dest: /etc/mesos-{{mesos_role}}.env
  notify: start mesos-{{mesos_role}}
