#!/bin/sh

EXEC=/opt/zookeeper/bin/zkServer.sh
PIDFILE=/var/lib/zookeeper/zookeeper_server.pid
USER=nobody
###############
# SysV Init Information
# chkconfig: - 60 91
# description: zookeeper is the zookeeper daemon.
### BEGIN INIT INFO
# Provides: zookeeper
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Should-Start: $syslog $named
# Should-Stop: $syslog $named
# Short-Description: start and stop zookeeper
# Description: zookeeper daemon
### END INIT INFO


function checkUser() {
  if [ `id -u` -ne 0 ]; then
    echo "You need root privileges to run this script"
    exit 4
  fi
}
checkUser

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed we will restarting it"
            su -s /bin/bash $USER -c   "$EXEC restart"
        else
            echo "Starting zookeeper server..."
        su -s /bin/bash $USER -c   "$EXEC start"
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping ..."
            su -s /bin/bash $USER -c   "$EXEC stop"
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Zookeeper to shutdown ..."
                sleep 1
            done
            rm -rf $PIDFILE
            echo "Zookeeper stopped"
        fi
        ;;
    status)
        PID=$(cat $PIDFILE)
        if [ ! -x /proc/${PID} ]
        then
           echo 'Zookeeper is not running'
        else
            su -s /bin/bash $USER -c   "$EXEC status"
            echo "Zookeeper is running ($PID)"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac
